### ISSUE TITLE
Package only works when r>s

### ISSUE THREAD

**Issue by vermouthmjl** [chrisaddy/rrr#2]
Hi,

I tried to play with rrr earlier, and saw that the functions only work with r>s.
If when trying to compile the vignette, we only use the 2 first columns of tobacco_x, trace_rank, rrr, and residuals give the following error
`Error in sqrtm %*% cov_yx : non-conformable arguments`

To fix this, I created a pull request https://github.com/chrisaddy/rrr/pull/1

Thank you.

**Comment by pllop448** [comment]
Hi, could you solve this problem? Thank you.

**Comment by vermouthmjl** [comment]
Hi @pllop448 
This reposed seemed abandoned since several years...
But you could pull the code from my pull request https://github.com/chrisaddy/rrr/pull/1. It solves this problem.
